object frmSaveReport: TfrmSaveReport
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Save Report'
  ClientHeight = 196
  ClientWidth = 289
  Color = clBtnFace
  DefaultMonitor = dmDesktop
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  DesignSize = (
    289
    196)
  PixelsPerInch = 96
  TextHeight = 13
  object btSave: TcxButton
    Left = 96
    Top = 160
    Width = 88
    Height = 28
    Anchors = [akRight, akBottom]
    Caption = 'Save'
    LookAndFeel.SkinName = 'VS2010'
    TabOrder = 0
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    OnClick = btSaveClick
  end
  object btCancel: TcxButton
    Left = 193
    Top = 160
    Width = 88
    Height = 28
    Anchors = [akRight, akBottom]
    Caption = 'Cancel'
    LookAndFeel.SkinName = 'VS2010'
    ModalResult = 2
    TabOrder = 1
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    ExplicitTop = 147
  end
  object gbItems: TcxGroupBox
    Left = 8
    Top = 8
    Caption = ' Save following items '
    TabOrder = 2
    Transparent = True
    Height = 129
    Width = 273
    object chbFiles: TcxCheckBox
      Left = 128
      Top = 73
      AutoSize = False
      Caption = 'Files'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 0
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbClipboard: TcxCheckBox
      Left = 128
      Top = 46
      AutoSize = False
      Caption = 'Clipboard'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 1
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbPrinters: TcxCheckBox
      Left = 128
      Top = 21
      AutoSize = False
      Caption = 'Printers'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 2
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbScreenshots: TcxCheckBox
      Left = 12
      Top = 21
      AutoSize = False
      Caption = 'Screenshots'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 3
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbKeystrokes: TcxCheckBox
      Left = 12
      Top = 46
      AutoSize = False
      Caption = 'Keystrokes'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 4
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbWebsites: TcxCheckBox
      Left = 12
      Top = 73
      AutoSize = False
      Caption = 'Websites'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 5
      Transparent = True
      Height = 19
      Width = 100
    end
    object chbApps: TcxCheckBox
      Left = 12
      Top = 98
      AutoSize = False
      Caption = 'Applications'
      ParentFont = False
      State = cbsChecked
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -11
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.LookAndFeel.SkinName = 'VS2010'
      Style.IsFontAssigned = True
      StyleDisabled.LookAndFeel.SkinName = 'VS2010'
      StyleFocused.LookAndFeel.SkinName = 'VS2010'
      StyleHot.LookAndFeel.SkinName = 'VS2010'
      TabOrder = 6
      Transparent = True
      Height = 19
      Width = 100
    end
  end
  object lbSaving: TcxLabel
    Left = 8
    Top = 139
    AutoSize = False
    Caption = 'Saving... please wait'
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -11
    Style.Font.Name = 'Tahoma'
    Style.Font.Style = []
    Style.TextColor = clRed
    Style.IsFontAssigned = True
    Properties.Alignment.Horz = taCenter
    Visible = False
    Height = 17
    Width = 273
    AnchorX = 145
  end
  object SaveDialog: TSaveDialog
    DefaultExt = 'zip'
    Filter = 'ZIP Archive|*.zip'
    Left = 228
    Top = 28
  end
  object AbZipper: TAbZipper
    AutoSave = False
    DOSMode = False
    Left = 228
    Top = 76
  end
end
